version: "3.9"

services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=development
      - NEXT_TELEMETRY_DISABLED=1
    volumes:
      - ./:/app
      - /app/node_modules
    command: ["pnpm","dev","-p","3000","-H","0.0.0.0"]
